Getting Started with Plugins
----------------------------

This documentation will guide you through the basic steps to run ImageJ with the plugins.

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   starting/instalation


Additional Notes
----------------

This part of the guide, which is mostly prose, begins with some
background information about Python, then focuses on next steps.

.. toctree::
  :maxdepth: 1

  support/faq
  support/error


Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
